# Generated by Django 5.1.2 on 2024-11-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text1', models.CharField(max_length=200)),
                ('question_text2', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BaseClass',
        ),
    ]
