# Generated by Django 5.1.2 on 2024-11-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_class_code_class_day_of_week_class_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
