# Generated by Django 5.1.2 on 2024-11-30 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_groupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupvote',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.group'),
        ),
    ]
