# Generated by Django 5.1.2 on 2024-11-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_groupvote_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
