# Generated by Django 5.1.2 on 2024-11-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日'), (7, '特養日')], default=0, null=True),
        ),
    ]
