# Generated by Django 5.1.2 on 2024-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_class_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日'), (7, '特曜日')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='field',
            field=models.IntegerField(blank=True, choices=[(1, '教養教育科目 人文分野'), (2, '教養教育科目 社会分野'), (3, '教養教育科目 自然分野'), (4, '教養教育科目 ライフデザイン分野'), (5, '宗教教育科目'), (6, '保健体育科目'), (7, '外国語科目'), (8, '日本事情'), (9, '専門（開発中）')], null=True),
        ),
    ]
