# Generated by Django 5.1.2 on 2024-11-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_alter_class_day_of_week_alter_class_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GroupVote',
        ),
    ]
