# Generated by Django 5.1.2 on 2024-12-05 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_group_vote_delete_groupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='BadComment',
            field=models.CharField(default='----', max_length=400),
        ),
        migrations.AddField(
            model_name='question',
            name='Class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.class'),
        ),
        migrations.AddField(
            model_name='question',
            name='GoodComment',
            field=models.CharField(default='----', max_length=400),
        ),
        migrations.AddField(
            model_name='question',
            name='OtherComment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='credit',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='homework',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='passion',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='recommend',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.CharField(default='----', max_length=50),
        ),
    ]
