# Generated by Django 5.1.2 on 2024-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_question_badcomment_question_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
