# Generated by Django 5.1.2 on 2024-12-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_question_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
