# Generated by Django 5.1.2 on 2024-12-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_class_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Answer',
        ),
    ]
