# Generated by Django 5.1.3 on 2024-12-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_rename_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, '前期'), (2, '後期'), (3, '通年')], default=0, null=True),
        ),
    ]
