# Generated by Django 5.1.2 on 2024-12-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_class_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='field',
            field=models.IntegerField(blank=True, choices=[(1, '教養教育科目 人文分野'), (2, '教養教育科目 社会分野'), (3, '教養教育科目 自然分野'), (4, '教養教育科目 ライフデザイン分野')], null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1時限'), (2, '2時限'), (3, '3時限'), (4, '4時限'), (5, '5時限'), (6, '6時限'), (7, '7時限'), (8, '特曜日')], default=0, null=True),
        ),
    ]
