services:
  web:
    build: .
    container_name: reverserate_web
    command: gunicorn --bind orange-997.komazawa-u.ac.jp:8000 mysite.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8081:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - UID=${UID}
      - GID=${GID}
    restart: unless-stopped

volumes:
  static_volume: 