services:
  web:
    build: .
    container_name: reverserate_web
    command: [ "/bin/sh", "-c", "gunicorn -w $(($(nproc) * 2 + 1)) --bind 0.0.0.0:8080 mysite.wsgi:application" ]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - UID=${UID}
      - GID=${GID}
    restart: unless-stopped

volumes:
  static_volume: 