# Generated by Django 5.1.2 on 2024-12-17 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='day_of_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日'), (7, '特曜日')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.IntegerField(blank=True, choices=[(1, '教養教育科目 人文分野'), (2, '教養教育科目 社会分野'), (3, '教養教育科目 自然分野'), (4, '教養教育科目 ライフデザイン分野')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.IntegerField(blank=True, default=0, null=True)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(blank=True, choices=[(1, '1時限'), (2, '2時限'), (3, '3時限'), (4, '4時限'), (5, '5時限'), (6, '6時限'), (7, '7時限'), (8, '特曜日')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True, choices=[(1, '前期'), (2, '後期'), (3, '通年')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text1', models.CharField(max_length=200)),
                ('question_text2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('credit', models.CharField(default='----', max_length=50)),
                ('score', models.CharField(default='----', max_length=50)),
                ('homework', models.CharField(default='----', max_length=50)),
                ('explanation', models.CharField(default='----', max_length=50)),
                ('passion', models.CharField(default='----', max_length=50)),
                ('recommend', models.CharField(default='----', max_length=50)),
                ('GoodComment', models.CharField(default='----', max_length=400)),
                ('BadComment', models.CharField(default='----', max_length=400)),
                ('OtherComment', models.CharField(blank=True, max_length=400, null=True)),
                ('Class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_import.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='codes',
            field=models.ManyToManyField(blank=True, to='data_import.code'),
        ),
        migrations.AddField(
            model_name='class',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, to='data_import.day_of_week'),
        ),
        migrations.AddField(
            model_name='class',
            name='fields',
            field=models.ManyToManyField(blank=True, to='data_import.field'),
        ),
        migrations.AddField(
            model_name='class',
            name='period',
            field=models.ManyToManyField(blank=True, to='data_import.period'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ManyToManyField(blank=True, to='data_import.semester'),
        ),
    ]
