# Generated by Django 5.1.2 on 2024-12-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
