# Generated by Django 5.1.2 on 2024-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_rename_codes_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day_of_week',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日'), (7, '特曜日')], default=0),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.IntegerField(choices=[(1, '1時限'), (2, '2時限'), (3, '3時限'), (4, '4時限'), (5, '5時限'), (6, '6時限'), (7, '7時限'), (8, '特曜日')], default=0),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(choices=[(1, '前期'), (2, '後期'), (3, '通年')], default=0),
        ),
    ]
