# Generated by Django 5.1.2 on 2024-12-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_alter_code_code_alter_day_of_week_day_of_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='days_of_week',
            new_name='day_of_week',
        ),
    ]
