# Generated by Django 5.1.3 on 2025-01-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_rename_days_of_week_class_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.IntegerField(choices=[(1, '1時限'), (2, '2時限'), (3, '3時限'), (4, '4時限'), (5, '5時限'), (6, '6時限'), (7, '7時限')], default=0),
        ),
    ]
