# Generated by Django 5.1.3 on 2025-01-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_alter_period_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='fields',
            new_name='field',
        ),
    ]
