# Generated by Django 5.1.3 on 2025-02-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_rename_fields_class_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='vote',
        ),
        migrations.AddField(
            model_name='answer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_import.group'),
        ),
    ]
