# Generated by Django 5.1.3 on 2025-02-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_remove_group_code_remove_group_vote_answer_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='score',
            new_name='late',
        ),
        migrations.AlterField(
            model_name='answer',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='data_import.group'),
        ),
    ]
