# Generated by Django 5.1.3 on 2025-02-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0009_rename_score_answer_late_alter_answer_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='late',
            new_name='score',
        ),
    ]
